# Generated by Django 4.2.1 on 2023-06-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="redactor",
            name="img",
            field=models.ImageField(
                default="default.png",
                upload_to="user_images",
                verbose_name="Redactor's photo",
            ),
        ),
        migrations.AlterField(
            model_name="redactor",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
